### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by tonybaltovski** [LORD-MicroStrain/ROS-MSCL#117]
Could you please do a new release?  We could really use a udev rule changes.

**Comment by robbiefish** [comment]
Hi @tonybaltovski, the udev rules have not been changed since we released [`2.4.1`](https://github.com/LORD-MicroStrain/microstrain_inertial/blob/2.4.1/microstrain_inertial_driver/debian/udev) for ROS and [`2.4.0`](https://github.com/LORD-MicroStrain/microstrain_inertial/blob/ros2-2.4.0/microstrain_inertial_driver/debian/udev) for ROS2. Can you please explain why we would need to do a new release?

**Comment by tonybaltovski** [comment]
Sorry, I missed it was in `2.4.1` for ROS1.  Thanks!
