### ISSUE TITLE
MSCL_LIB_PATH     linked by target "microstrain_inertial_driver" in directory /home/hhc/Desktop/lord/lord_ws_intact/src/microstrain_inertial

### ISSUE THREAD

**Issue by HoiCeong** [LORD-MicroStrain/ROS-MSCL#167]
here is the log:

Please set them or make sure they are set and tested correctly in the CMake files:
MSCL_LIB_PATH
    linked by target "microstrain_inertial_driver" in directory /home/hhc/Desktop/lord/lord_ws_intact/src/microstrain_inertial/microstrain_inertial_driver

-- Configuring incomplete, errors occurred!

**Comment by robbiefish** [comment]
Hi @HoiCeong,

1. What version of the driver are you using? Are you just cloning directly from github?
2. Are these all of the logs from a fresh build? I would expect to see more logs with some more helpful errors.
3. The driver will attempt to download MSCL at build time. If you have internet access this should work, but if you do not have internet access, or do not want to install the library automatically, you can download MSCL and specify the path manually with the `MSCL_LIB_PATH` variable. More information can be found [here](https://github.com/LORD-MicroStrain/microstrain_inertial#mscl)

**Comment by HoiCeong** [comment]
> 
Thanks for your reply.

1. I downloaded the **c++-mscl_64.3.0_amd64.deb**, and excuted : **sudo dpkg -i c++-mscl_64.3.0_amd64.deb, sudo apt install -f** to install the driver. And then I cloned the project and **catkin_make**.
2. here is the LOG:
``` c++
-- +++ processing catkin package: 'microstrain_inertial_driver'
-- ==> add_subdirectory(microstrain_inertial/microstrain_inertial_driver)
-- Looking for MSCL tag v64.2.2 on github
/bin/bash: jq: command not found
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
-- Downloading c++-mscl_64.2.2_amd64.deb to /home/xxxx/Desktop/lord/lord_ws_intact/build/microstrain_inertial/microstrain_inertial_driver/c++-mscl_64.2.2_amd64.deb
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
dpkg-deb: error: failed to read archive '/home/xxxx/Desktop/lord/lord_ws_intact/build/microstrain_inertial/microstrain_inertial_driver/c++-mscl_64.2.2_amd64.deb': No such file or directory
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MSCL_LIB_PATH
    linked by target "microstrain_inertial_driver" in directory /home/xxxx/Desktop/lord/lord_ws_intact/src/microstrain_inertial/microstrain_inertial_driver

-- Configuring incomplete, errors occurred!
See also "/home/xxxx/Desktop/lord/lord_ws_intact/build/CMakeFiles/CMakeOutput.log".
See also "/home/xxxx/Desktop/lord/lord_ws_intact/build/CMakeFiles/CMakeError.log".
Makefile:2798: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

3. "you can download MSCL and specify the path manually with the MSCL_LIB_PATH variable"——In which file can I add this variable "MSCL_LIB_PATH" to specify the path manually.

**Comment by robbiefish** [comment]
So it looks like you have a couple problems with both solutions.

* If you want to download MSCL automatically:
  1. it looks like curl is unable to verify the legitimacy of the server. This often happens when you are behind a corporate proxy, and the proxy is injecting it's certificate into requests. It this is the case, you can attempt to obtain your proxies certificate authority by contacting your IT department, and then following [this guide](https://ubuntu.com/server/docs/security-trust-store) to trust that certificate.
  2. You need to install rosdeps as you appear to be missing `jq` which is a required dependency when downloading MSCL. You can do this by running `rosdep install --from-paths /home/hhc/Desktop/lord/lord_ws_intact/src/ -iry`

* If you want to use the version that you installed you must specify `-DMSCL_DIR` when building the driver. In your case, since it looks like you installed it in the default location, you would run `catkin_make -DMSCL_DIR=/usr/share/c++-mscl`

Please note that for both options, you should install rosdeps with `rosdep install --from-paths /home/hhc/Desktop/lord/lord_ws_intact/src/ -iry`
