### ISSUE TITLE
an instance of 'mscl::Error_MipCmdFailed'   what():  The DeclinationSource command has failed.

### ISSUE THREAD

**Issue by Vikash-iitd** [LORD-MicroStrain/ROS-MSCL#168]
Hi,
I tried to launch microstrain.launch using `roslaunch microstrain_inertial_driver microstrain.launch` but it throws error. I also tried by setting  `baudrate``:=921600` but still same error was there . In windows software -`SensorConnect`-  it's publishing some Hex Data. but when I tried to launch using `ros package LORD-MicroStrain/microstrain_inertial `it gives errors .

i am attaching screenshot below....

![Screenshot from 2022-07-22 12-09-18](https://user-images.githubusercontent.com/109785141/180379007-654f676b-089d-4f03-9b55-50b0ba7437c0.png)
![Screenshot from 2022-07-22 12-09-29](https://user-images.githubusercontent.com/109785141/180379000-8266c88b-68e5-4058-8ae3-93265761c9f1.png)
![Screenshot from 2022-07-22 12-09-40](https://user-images.githubusercontent.com/109785141/180378991-abc488b4-b828-4fae-b3e7-bf625e99600a.png)

![Screenshot from 2022-07-22 11-57-27](https://user-images.githubusercontent.com/109785141/180378735-c2a37779-1525-4808-bbba-176971360d38.png)

above you can see detailed output and error.

also `rostopic list` command also `not showing any topic` for lord-imu. Also searched for `mscl::Error_MipCmd` but couldn't find anything.

Thanks

**Comment by robbiefish** [comment]
Hi @Vikash-iitd 

This error is due to the fact that the CV7 does not support the default [`filter_declination_source`](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/main/config/params.yml#L224). The comment has been updated to point this out, but you will need to change this to either `1` or `3`. For more information on what the different settings do, please see the documenentation for [Magnetic Field Declination Source Control (0x0D,0x43)](https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Commands/filter_command/data/mip_filter_magnetic_declination_source.htm?Highlight=declination%20source)

If you already have a `params.yml` file you are using to configure the driver, you can simply add the following line to your file. If not, you should make a new yml file with the following contents:

```yaml
filter_declination_source: 1
```

Then you can provide the file to the `params_file` option when launching the node. Assuming you made the file at `/home/user/cv7_params.yml` you would run the node like so:

```bash
roslaunch microstrain_inertial_driver microstrain.launch params_file:=/home/user/cv7_params.yml
```

**Comment by Vikash-iitd** [comment]
Hey , 
I tried what you suggested and the node moved somewhat further but then it again showed some error . I read param.yaml file comments and and tried to change according to that and it also worked and further moved ahead. now I am stuck in below error, please look into it.
![Screenshot from 2022-07-27 13-40-44](https://user-images.githubusercontent.com/109785141/181196887-a6e3ef1f-3226-4812-a48d-7189543e120f.png)
![Screenshot from 2022-07-27 13-41-03](https://user-images.githubusercontent.com/109785141/181196928-58c432fb-d6c7-4f2c-a80a-2d9c56b6e887.png)
![Screenshot from 2022-07-27 13-41-13](https://user-images.githubusercontent.com/109785141/181196949-8666c81c-25c9-4674-b0a8-33b5ff9ef046.png)
![Screenshot from 2022-07-27 13-41-19](https://user-images.githubusercontent.com/109785141/181196987-56ce2bb2-9cc6-4999-9ef9-a3f2c2ea3239.png)

This error is somewhat related to `Aiding measurement control ` in param.yaml file I guess . please look into it.

**Comment by robbiefish** [comment]
It looks like you are using an old version of the driver. The version of the driver you are using does not work with the CV7.

* If you are building from source, either build from the `ros` branch or tag `2.6.0` or above.
* If installing from the ROS package index, please uninstall and reinstall the driver to get the most recent version like so (replace ROS_DISTRO with your ROS version e.g. noetic, melodic, etc.):
    ```bash
    sudo apt-get update
    sudo apt-get purge ros-ROS_DISTRO-microstrain-inertial-driver
    sudo apt-get install ros-ROS_DISTRO-microstrain-inertial-driver
    ```

After the driver has been updated, you should be able to run with the same command

**Comment by Vikash-iitd** [comment]
Hey , Thanks for your help. I tried this and finally it worked!!
