### ISSUE TITLE
Issues with Data Quality of 3DM-GQ7 GNSS2 and Filter

### ISSUE THREAD

**Issue by JokerJohn** [LORD-MicroStrain/ROS-MSCL#259]
**Describe the bug**
We've been using the 3DM-GQ7 as instructed, setting up and calibrating it according to the provided tutorial and utilizing the ROS1 driver for data collection. However, we've run into the following issues:

1. The device is remarkably unstable. We often encounter scenarios where the data suddenly disappears after a collection period, or the satellite count abruptly drops to zero. This necessitates device and driver restarts or resets using the software on the Windows host machine. The performance of this device contrasts starkly with the stability of previous 3DM products (like GX5). Has this product been launched without adequate stability testing? Despite the circumstances, we would appreciate any suggestions for possible resolutions.

2. The duration required to initialize the filter or GNSS fix varies greatly. We've tried static and dynamic initializations: at best, initialization is completed within half a minute, but it often takes as long as 20-30 minutes. We would welcome any advice on how to address this issue.

3. The quality of one of the dual-antenna GNSS is consistently lower than the other. If you look at images 'a' and 'b' below, the difference, particularly in the z-axis data, between GNSS-right and left and the filter is significant. This discrepancy is evident in many of our collected data sequences.
![image](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/25702851/985e0ef5-aedd-4418-93e8-99fc62271d17)
![image](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/25702851/d5b0cafe-96a0-4261-8b06-5c7d8539db27)

4. The results from the filter are occasionally unstable. Even when we disabled modules like magnetic assistance that are negatively optimized, we noticed that the z-axis discrepancy at the same position is often significant. We suspect this could be due to issues with some parameter settings. Please refer to images 'c' and 'd' below. （green：gnss-left, white:gnss-right, red:filter）

![image](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/25702851/162d3651-5c88-486a-8d05-4a2dd4de4365)

![image](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/25702851/fa934923-e11f-42e0-ab45-bba90931afc8)

**Comment by nathanmillermicrostrain** [comment]
Hello,

The GQ7 is more sophisticated than the GX5 and takes a bit more care to setup... the instability that you are seeing above indicates something is wrong with your "gnss_right" solution (as you've pointed out.)  My guess would be one of the following:

1. Placement of the antenna near an interference source.  The receivers in the GQ7 are L1/L2, and the L2 signal is more susceptible to EMI interference from other parts of your system.  This could be a computer, USB hub, lidar, or anything else with fast-switching logic.  Please ensure you are not mounted close to these types of devices. 

2. Damage to the antenna cable.  Sometimes the cables get kinked or damaged during installation and it may be difficult to see.  Please check the "gnss_right" cable specifically for damage.  You can swap cables/installation locations to see if the issue tracks the antenna or not.

There should be virtually no difference in the quality of fix between the two GNSS modules, so one of the items above is likely causing the issue.  

On the topic of initialization time... if you have poor quality on one of the antennas, the GQ7 will not be able to calculate a good dual antenna heading fix and, therefore, won't be able to initialize if that is the only heading source configured for initialization.  This effect can also degrade in-run performance.

One of the features of the driver is being able to configure it for factory support and record a raw binary file to send to us.  If you would like to do that so that we can look at all the raw information, we can take this support request to email.  Let me know if you want to go this route.

Thanks,

Nathan

**Comment by JokerJohn** [comment]
Thank you for your detailed response. I will close this issue for now and will reopen it once I have gathered new test data. At that time, I would appreciate your assistance in troubleshooting the issue
