### ISSUE TITLE
Can't use the low-pass filter feature

### ISSUE THREAD

**Issue by ozeryeden** [LORD-MicroStrain/ROS-MSCL#336]
hi,

We have configured the cutoff frequency of the low-pass filter in the SensorConnect software as follows:
![low_pass_filter_sensorconnect](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/153181868/8de8d762-ce59-484d-98ba-1036d464f3a4)

Below are the results of the acceleration data (published in '/imu/data' topic) with the cutoff frequency set to 500 Hz (default) and 1 Hz, using the most updated ros-driver (https://github.com/LORD-MicroStrain/microstrain_inertial).

500 Hz:
![500hz_results](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/153181868/0af4d25d-d441-4be2-acbe-8da72749ff98)

1 Hz:
![1hz_results](https://github.com/LORD-MicroStrain/microstrain_inertial/assets/153181868/8066e389-dbbd-4548-b3f0-29b6001940bc)

As you can see, there appears to be no change in the data.
Important to note that in the MIP software, the low-pass filter does seem to have an affect on the output data.

Am I using this feature correctly? if not could you please provide more details on how to correctly use it?

Thank you,
Eden

**Comment by robbiefish** [comment]
Hi @ozeryeden,

Apologies for the delay. you appear to be using the feature correctly, the issue is in how the ROS driver publishes data.

It is noted in [the wiki](https://wiki.ros.org/microstrain_inertial_driver#Standard_ROS_Messages) that the `linear_acceleration` and `angular_velocity` fields are populated by DeltaVelocity and DeltaTheta divided by time since they were last sampled.

As such, the low pass filter will have no effect on the data in that message, since it is only applied to the "Scaled" fields such as "ScaledAccel", "ScaledGyro", etc.

I am not sure exactly what your use-case is for using the low pass filter, but if you simply want to remove noise, you can reduce the `imu_data_rate` in the driver for now.

I will be adding the ability to use the scaled measurements and configure the low pass filter in the coming days though.

**Comment by robbiefish** [comment]
The ability to configure the low pass filter was added in `4.4.0`
