### ISSUE TITLE
How to connect EMLID with 3DM-GQ7 and 3DMRTK

### ISSUE THREAD

**Issue by jinwen15** [LORD-MicroStrain/ROS-MSCL#360]
So we want to mount 3DM-GQ7 and 3DM-RTK on a robot and run it underground, which means it cannot see the satellite and receive corrections. We plan to set up Emlid Reach RS2 as a base station that is connected to NTRIP, and then set up 3DM-GQ7 with 3DM-RTK like a rover, we want all these devices to communicate with each other so that 3DM-GQ7 and 3DM-RTK can receive corrections from RS2. I wonder if it's possible to do it? We are using Ubuntu 18.04 to operate 3DM-GQ7.
Can anyone give an answer to this? Appreciate any kind of help.

**Comment by robbiefish** [comment]
Hi @jinwen15, the 3DM-RTK is a cell modem meant to receive corrections from our cloud service over the cell network. If you wanted to receive corrections from the Reach, you would need to connect the aux port of the GQ7 to a radio that communicates with the Reach, or connect the aux port to a computer, and send the RTCM corrections received from the Reach to the aux port.

The bigger issue here is that the Reach will only provide you with the corrections. The GQ7 would still need to be able to see the sky in order to get a good GNSS fix, so what you are trying to do will not be possible with GNSS or RTK. If you are trying to do GNSS denied navigation, I would suggest taking a look at the [CV7-INS](https://www.microstrain.com/inertial-sensors/3DM-CV7-INS) or [GV7-INS](https://www.microstrain.com/inertial-sensors/3DM-GV7-INS).

If you have any further questions about this topic, or our sensors, please open a ticket at https://support.microstrain.com where our inertial experts can provide more assistance
